### ISSUE TITLE
TypeError: Cannot read property 'tarball' of undefined

### ISSUE THREAD

**Issue by austinfrey** [depjs/dep#63]
### Summary
Getting the following error when installing any module.
```bash
Resolving dependencies
TypeError: Cannot read property 'tarball' of undefined
    at Request.request.get.on.on (/home/austin/.nvm/versions/node/v8.11.1/lib/node_modules/dep/lib/install/resolver/fetchers/registry.js:28:32)
    at emitOne (events.js:121:20)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/austin/.nvm/versions/node/v8.11.1/lib/node_modules/dep/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
Current setup:
```bash
$ node -v
v8.11.1

$ npm -v
6.0.1

$ dep -v
0.18.0

$ uname -a
Linux lappy-88 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
```
I should also mention I'm using `nvm` to manage npm and node.
### Steps to reproduce behavior
```bash
$ npm install -g dep
$ npm init -y
$ dep install hyperscript
```

### Expected behavior
`dep install <module>` should successfully install the package

### Actual behavior
Throws the above listed error

**Comment by austinfrey** [comment]
Looking at this a bit more, when making a request for a package here: https://github.com/depjs/dep/blob/f8c97a68fa2a98736558bcccd6151e7b2409cbe8/lib/install/resolver/fetchers/registry.js#L14 the following `.on('data', (chunk)..)` handler returns `"{"code":"MethodNotAllowedError","message":"GET is not allowed"}"` as the chunk, so in this line: https://github.com/depjs/dep/blob/f8c97a68fa2a98736558bcccd6151e7b2409cbe8/lib/install/resolver/fetchers/registry.js#L28 we can't get the tarball from `body.dist` since it's undefined. I'm not sure why GET's are not allowed or why it seems to work for others and not me, but that's what I'm seeing.

**Comment by austinfrey** [comment]
@watilde thanks for the speedy reply. I'll try it out this afternoon!
